---
title: "AgingEarRegen"
author: "Justin Varholick"
date: "2023-07-11"
output: html_document
---
#packages
```{r}
library(tidyverse)
library(ggplot2)
library(see)
library(cowplot)
library(extrafont)

library(lme4)
library(lmerTest)

```

#import data
```{r}
daystoclose <- read.csv("data/EarDaysToClose_Data.csv")
areaperday <- read.csv("data/EarAreaPerDay_Data.csv")
areaperday <- left_join(areaperday, daystoclose, by="AnimalID")
```

#repeated measures graph, raw
```{r}

#animals to exclude due to insufficient data
exclude <- c("925878-1", "925878-2", "1001363-1", "1001363-2", "990342-1", "990342-2")
areaperday1 <- filter(areaperday, !AnimalID %in% exclude)
areaperday1 <- filter(areaperday1, !DayPostWounding %in% c(0))
areaperday1 <- mutate(areaperday1, AgeinMonths=(AgeAtInjury/30.417))

ggplot(areaperday1, aes(DayPostWounding, Area, color=AgeinMonths))+
  geom_point2(size = 3, alpha = 0.5) +
  scale_x_continuous(breaks=seq(0,110, 5))+
  geom_hline(yintercept=12.56637061, linetype="dashed", color="black")+
  xlab("days post injury") + ylab(bquote("Area "(mm^2)))+
  labs(color="Age \nin Months")+
  theme_cowplot()+
  scale_color_gradient2(low = "#5ec962", mid = "#21918c", high = "#3b528b", midpoint = 6) +
  theme(axis.text.x=element_text(angle=90, vjust=0.75))

plota <- ggplot(areaperday1, aes(DayPostWounding, Area, fill=AgeinMonths))+
  geom_point(size = 1, pch = 21, color = "black") +
  scale_x_continuous(breaks=seq(0,110, 5))+
  geom_hline(yintercept=12.56637061, linetype="dashed", color="black")+
  xlab("days post injury") + ylab(bquote("Area "(mm^2)))+
  labs(fill="Age \nin Months")+
  theme_cowplot(font_size = 8)+
  scale_fill_gradient2(low = "#fde725", mid = "#22A884", high = "#414487", midpoint = 6) +
  theme(axis.text.x=element_text(angle=90, vjust=0.75))
plota

ggsave("Figures/EarClose_Time_Age_viridis.pdf", dpi=300, width=180, height=90, unit="mm")

```

#growth model
```{r}
growth_data <- filter(areaperday1, DayPostWounding!=0)
t <- poly(1:max(growth_data$DayPostWounding), 3)
growth_data[, paste("ot", 1:3, sep="")] <- t[growth_data$DayPostWounding, 1:3]

#I didn't use the ot values in the published model 

ear_gr_base <- lmer(Area ~ DayPostWounding + (DayPostWounding| CageID:AnimalID),
                  data=growth_data, REML=FALSE)

ear_gr_m0 <- lmer(Area ~ DayPostWounding + AgeAtInjury +
                      (DayPostWounding | CageID:AnimalID),
                    data=growth_data, REML=FALSE)

ear_gr_m1 <- lmer(Area ~ DayPostWounding + AgeCat + 
                    (DayPostWounding | CageID:AnimalID),
                  data=growth_data, REML=FALSE)

anova(ear_gr_m0) 
anova(ear_gr_m1) #this model accounts for more variability, and I can add in the ≥ 22mo in the plot
summary(ear_gr_m1)
```
#growth model plot, this isn't worth it.
```{r}
data.comp <- data.frame(growth_data, GCA_Full=fitted(ear_gr_m1))

ggplot(growth_data, aes(DayPostWounding, Area, color=AgeCat))+
  stat_summary(fun.data=mean_se, geom="linerange", show.legend=FALSE)+
  geom_point(stat="summary", fun=mean, size=2)+
  stat_summary(aes(y=fitted(ear_gr_m1), linetype=AgeCat), fun=mean, geom="line", size=1.25)+
  geom_hline(yintercept=12.566,linetype="dashed", color="black")+
  scale_y_continuous(breaks=c(0,5,10,12.566), labels=c(0,5,10,12.566))+
  scale_color_npg()+
  xlab("Day Post Wounding")+ ylab(Earhole~Area~(mm^2))+
  labs(color="AgeAtInjury", linetype="AgeAtInjury")

ggplot(growth_data, aes(DayPostWounding, Area, color=AgeCat))+
  geom_point() +
  stat_summary(aes(y=fitted(ear_gr_m1), linetype=AgeCat), fun=mean, geom="line", size=1.25)+
  geom_hline(yintercept=12.566,linetype="dashed", color="black")+
  scale_y_continuous(breaks=c(0,5,10,12.566), labels=c(0,5,10,12.566))+
  scale_color_npg()+
  xlab("Day Post Wounding")+ ylab(Earhole~Area~(mm^2))+
  labs(color="AgeAtInjury", linetype="AgeAtInjury")


```
#repeated measures graph, add in aged animals
```{r}

#animals to exclude due to insufficient data
areaperday2 <- areaperday %>% 
  filter(!DayPostWounding %in% c(0))

areaperday2$AgeCat <- factor(areaperday2$AgeCat, levels = c("3-4mo", "4-6mo", "6-9mo", "≥ 22mo"))


plotb <- ggplot(areaperday2, aes(DayPostWounding, Area, fill = AgeCat, color = AgeCat, shape = AgeCat))+
  geom_point(size = 1, alpha = 0.8) +
  geom_smooth(method = "loess", formula = "y ~ x", se = FALSE, linetype = "dashed", size = 0.5) +
  scale_x_continuous(breaks=seq(0,110, 5))+
  scale_y_continuous(breaks = c(0, 5, 10, 12.566, 15), 
                                labels = c("0", "5", "10", "12.566", "15")) +
  geom_hline(yintercept=12.56637061, linetype="dotted", color="black")+
  xlab("Days Post Injury") + ylab(bquote("Area "(mm^2)))+
  labs(fill="Age", color = "Age", shape = "Age")+
  theme_cowplot(font_size = 8)+
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#D55E00"))+
  scale_color_manual(values=c("#E69F00", "#56B4E9", "#009E73", "#D55E00"))+
  scale_shape_manual(values=c(16,16,16,17))+
  theme(axis.text.x=element_text(angle=90, vjust=0.75))
plotb

ggsave("Figures/EarClose_Time_Age+Aged_viridis.png", dpi=300, width=180, height=90, unit="mm")
```
# days to close graph
```{r}
daystoclose2 <- filter(daystoclose, AgeCat != "≥ 22mo")

plotc <- ggplot(daystoclose2, aes(AgeAtInjury, DaysToClose))+
  geom_jitter(size = 1, alpha = 0.8, aes(color = AgeCat)) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black", size = 0.5) +
  labs(x = "Age in Days", y = "Days to Close Ear",
       color = "Age") +
  scale_color_manual(values=c("#E69F00", "#56B4E9", "#009E73"))+
  theme_cowplot(font_size = 8) + theme(axis.text.x=element_text(angle=90, vjust=0.75))
plotc
```

# time to 50% of animals closed
```{r}
fiftypercent <- data.frame(AgeCat = c("3-4mo", "4-6mo", "6-9mo"),
                           days_when_50_percent = c(45, 50, 105))

plotd <- ggplot(fiftypercent, aes(AgeCat, days_when_50_percent, fill = AgeCat)) +
  geom_col(width = 0.75) +
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73")) +
  scale_y_continuous(expand = c(0,0)) +
  labs(fill = "Age", x = "", y = "Days Post Injury \nWhen 50% Have Closed Ear-Hole") +
  guides(fill = "none") +
  theme_cowplot(font_size = 8) +
  theme(axis.text.x=element_text(angle=45, vjust = 1, hjust = 1))

plotd
```
```{r}

```


```{r}
plot_grid(plotb, plotd,
          ncol = 2, labels = NULL, rel_widths = c(3,1))
ggsave("Figures/EarClose_Time_Panel.png", dpi = 300, width = 180, height = 55, unit = "mm")
```

